version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - model_cache:/app/model_cache
      - ./static:/app/static:ro
    environment:
      - APP_NAME=ML Model Service
      - DEBUG=false
      - MODEL_CACHE_DIR=/app/model_cache
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - ml-network

  # Optional: Nginx for static file serving and reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - ml-network
    profiles:
      - with-nginx

volumes:
  model_cache:
    driver: local

networks:
  ml-network:
    driver: bridge